FROM anapsix/alpine-java
MAINTAINER Ahmed
EXPOSE 8889
COPY player2-0.0.1-SNAPSHOT.jar /home/player2-0.0.1-SNAPSHOT.jar
CMD ["java","-jar", "-Dspring.profiles.active=docker","/home/player2-0.0.1-SNAPSHOT.jar"]
