FROM anapsix/alpine-java
MAINTAINER Ahmed
EXPOSE 8888
COPY player1-0.0.1-SNAPSHOT.jar /home/player1-0.0.1-SNAPSHOT.jar
CMD ["java","-jar", "-Dspring.profiles.active=docker","/home/player1-0.0.1-SNAPSHOT.jar"]
